### ISSUE TITLE
AdClear crash when update Android 11

### ISSUE THREAD

**Issue by hhbaieb** [SEVENNetworks/AdClear-Open-Source-Issue-Tracker#113]
**Describe the bug**
I just updated my Xiaomi Redmi Note 8 pro to Android 11. AdClear no longer works.  When I try to open the app, it appears briefly, then it disappears. 

**To Reproduce**
1. Install AdClear in Android 11 system
2. open AdClear 
3. it appears briefly, then it disappears. 

**Expected behavior**
AdClear  crash

**Screenshots**
N/A

**Environment (please complete the following information):**
 - Device: Xiaomi Redmi Note 8 pro
 - OS: MIUI 12.5.1 (Android 11 RP1A.200720.011)
 - AdClear version 9.15.0.815-ga

**Additional context**
None

**Comment by legolego** [comment]
I have the same issue with a OnePlus 8 on Android 11(build 11.0.3.5.IN55CB) and AdClear 9.15.0.815-beta. It worked fine in Android 10.
